name: Build, Sign, and Release MSIX

on:
  release:
    types: [published]

jobs:
  sign-msix:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore otp.sln

      - name: Publish MSIX package
        run: |
          dotnet publish otp/otp.csproj -c Release -p:Platform=x64

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Locate and Sign MSIX
        run: |
          $msix = Get-ChildItem -Recurse -Filter *.msix | Select-Object -First 1
          if (!$msix) {
            Write-Error "MSIX file not found"
            exit 1
          }

          echo "Found MSIX: $($msix.FullName)"
          echo "msix_path=$($msix.FullName)" >> $env:GITHUB_ENV

          cosign sign-blob --yes --output-certificate otp.pem --output-signature otp.sig "$($msix.FullName)"

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.msix_path }}
            otp.pem
            otp.sig
