name: Build, Sign, and Release MSIX

on:
  release:
    types: [published]

jobs:
  sign-msix:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore packages
        run: dotnet restore otp.sln

      - name: Build for x64 Release
        run: dotnet build --configuration Release --no-restore -p Platform=x64 otp.sln

      - name: Locate .msix file
        id: locate
        run: |
          $msix = Get-ChildItem -Recurse -Filter *.msix | Select-Object -First 1
          echo "msix_path=$($msix.FullName)" >> $env:GITHUB_ENV

      - name: Set up Cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Sign MSIX with Cosign
        run: |
          cosign sign-blob --yes --output-certificate otp.pem --output-signature otp.sig "$env:msix_path"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.msix_path }}
            otp.pem
            otp.sig
